#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
$SOURCE_DIR/base/install

source $SOURCE_DIR/config

cp $SOURCE_DIR/java/Procfile $SOURCE_DIR/utils/Procfile
echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
apt-get update
apt-get install -y software-properties-common haveged
add-apt-repository -y ppa:webupd8team/java
apt-get update
apt-get install -y --force-yes oracle-java8-installer
apt-get install -y --force-yes maven

echo "PermitUserEnvironment yes" >> /etc/ssh/sshd_config

# Configure timezone and locale
echo "Europe/Amsterdam" > /etc/timezone 
dpkg-reconfigure -f noninteractive tzdata

sed -i 's;\[ -f /home/application/apprc \] && source /home/application/apprc;#JAVA_HOME#;' /home/ubuntu/.profile
echo '[ -f /home/application/apprc ] && source /home/application/apprc' >> /home/ubuntu/.profile
