#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

XMX=${JAVA_MAX_MEMORY-128}
MAXPERM=${JAVA_MAX_PERM-128}

cd /home/application/current
java -XX:MaxPermSize=${MAXPERM}m -Xmx${XMX}m -jar tsuru-app.jar -Dserver.host=0.0.0.0 -Dserver.port=${PORT}
sleep 10
