#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

XMX=${JAVA_MAX_MEMORY-128}
TSURU_JAVA_OPTS=${TSURU_JAVA_OPTS}

cd /home/application/current
java -Dserver.host=0.0.0.0 -Dserver.port=${PORT} ${TSURU_JAVA_OPTS} -Xmx${XMX}m -jar tsuru-app.jar
sleep 10
