#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

XMX=${JAVA_MAX_MEMORY-256}
MAXPERM=${JAVA_MAX_PERM-128}

cd /home/application/current
grails --non-interactive -Dserver.host=0.0.0.0 -Dserver.port=8888 -Denable.jndi=true -Ddisable.auto.recompile=true -Dgrails.env=production run-app
