#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

XMX=${JAVA_MAX_MEMORY-256}
MAXPERM=${JAVA_MAX_PERM-128}
JAVA_AGENT=${JAVA_AGENT}

cd /home/application/current/build/libs
java -Dgrails.env=prod -jar current-${GRAILS_APP_VERSION}.war -XX:MaxPermSize=${MAXPERM}m -Xmx${XMX}m ${JAVA_AGENT} --server.host=0.0.0.0 --server.port=${PORT}
sleep 10
