#!/bin/bash -l

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

source /var/lib/tsuru/config

TSURU_JAVA_VERSION=${JAVA_VERSION-8}
case $TSURU_JAVA_VERSION in
8)
	java_to_use="java-8-oracle"
	;;
*)
	echo "WARNING: invalid Java version, please use \"8\". Using Java 8 as fallback."
	java_to_use="java-8-oracle"
	;;
esac

sudo update-java-alternatives -s $java_to_use > /dev/null
sed -i "s;export JAVA_HOME.*;export JAVA_HOME=/usr/lib/jvm/$java_to_use;" /home/ubuntu/.profile
sed -i "s;#JAVA_HOME#;export JAVA_HOME=/usr/lib/jvm/$java_to_use;" /home/ubuntu/.profile

mkdir -p /home/ubuntu/.ssh
chmod 700 /home/ubuntu/.ssh
echo "JAVA_HOME=/usr/lib/jvm/$java_to_use" > /home/ubuntu/.ssh/environment

TSURU_GRAILS_VERSION=${GRAILS_VERSION}
if [ -n "$TSURU_GRAILS_VERSION" ]; then
  gvm install grails $TSURU_GRAILS_VERSION
  gvm default grails $TSURU_GRAILS_VERSION
fi
/var/lib/tsuru/base/start
